### ISSUE TITLE
mixlib install attempts to install the current chef-client version instead of the latest on first attempt

### ISSUE THREAD

**Issue by demiph** [chef/mixlib-install#356]
# Version:

3.11

# Environment:

We are using the chef_client_updater cookbook to update all OS in our environment to the **latest** chef-client version. OSes in this environment are majorly Linux and Windows

# Scenario:

The chef_client_updater cookbook uses the mixlib-install library, but chef-client is frequently not updated on windows nodes from 2012R2 servers to windows 10. By looking at windows logs, we are able to see an attempt to upgrade but the MSI package that is downloaded is the chef-client version that we are upgrading from.

This is what an upgrade attempt from chef 16.12.3 to 16.13.16 looks like according to the logs
```
Starting upgrade at 04/09/2021 19:49:00

Beginning a Windows Installer transaction: C:\Windows\TEMP\chef-client-16.12.3-1-x64.msi. Client Process Id: 2028.

Ending a Windows Installer transaction: C:\Windows\TEMP\chef-client-16.12.3-1-x64.msi. Client Process Id: 2028.
```

We see nothing in the installation directory and no chef-client-16.13.16-1-x64.msi is downloaded at that instance. A re-run of the process then gives us 

```
Starting upgrade at 04/09/2021 22:14:00

Beginning a Windows Installer transaction: C:\Windows\TEMP\chef-client-16.13.16-1-x64.msi. Client Process Id: 13440.

Windows Installer installed the product. Product Name: Chef Infra Client v16.13.16. Product Version: 16.13.16.1. Product Language: 1033. Manufacturer: Chef Software, Inc.. Installation success or error status: 0.
```

Nothing is changed here in the cookbook, and the cookbook as always attempts to install the latest chef-client version

# Steps to Reproduce:

Attempt upgrading chef-client to the latest version immediately after a new release using mixlib-install

# Expected Result:

The current chef-client version is re-installed, and after a loop, it is able to update to the latest

# Actual Result:

The current chef-client version is re-installed, and after a loop, it is able to update to the latest

**Comment by tduffield** [comment]
Hi @demiph. 

I just want to clarify that your issue is related to the **timing** between the announcement of a new release via something like Discourse or the community slack and when you're able to download it via the chef_client_updater cookbook? 

If so, this is a known issue that is not actually directly related with mixlib-install. The actual issue is that various caching causes an "eventually consistent" availability of new versions via our APIs. We're constantly working to improve and/or reduce this window, but there are a lot of factors that can come into play. 

Unfortunately this is not an issue that can be resolved within the scope of `mixlib-install` so I am going to close this issue. We do have an internal card tracking the effort to reduce the time between promotion and availability via our APIs. I will link this issue to that card. 

If I have misinterpreted your issue, please feel free to re-open with additional clarifications.

Thanks!

**Comment by demiph** [comment]
Hi @tduffield 

In this case we are using the mixlib/versioning library to determine if there is new package of the latest stable stream of chef-client available. In this case, calling the library does show there is a new package however attempting to install it re-downloads the existing chef-client package. we only see this issue in a small time windows after a new chef-client package is made publicly available which also makes me guess at caching
